### PR TITLE
Fix saving sitemap definitions

### LINKED ISSUE #15: Success message says - Definition updated but file is not generated?
After installation of this plugin, I added a few definitions from CMS pages and on clicking save,  I got success message of "Definition updated" but while trying to access `website.com/sitemap.xml` , it gave 404!!

Anything I am missing?

I have WinterCMS 1.2.1 and I have used the `public` folder setup, do I need to symlink again?
i have proper permission for the `public` folder as well. 
What else shall I check to get the sitemap file?

### PR DESCRIPTION
**Pull request by mjauvin**
Fixes #15
Addresses https://github.com/wintercms/winter/issues/1219, https://github.com/wintercms/winter/issues/1222
Replaces #18

### CODE REVIEW

File: assets/js/sitemap-definitions.js [hunk 1]
```diff
@@ -49,11 +49,12 @@
             return result
         }
 
-        data.options.data['itemData'] = iterator($items)
+        var fieldName = $('div[data-control=sitemap-item-editor]').data('fieldName')
```
Comment (bennothommo) [inline assets/js/sitemap-definitions.js:52]: Just FYI, every single supported browser supports the use of `let` and `const`, so for all new JS code, we should use `const` unless we're very sure the variable needs to change, just to ensure there's no unintended side effects with the use of a variable.

```suggestion
        const fieldName = $('div[data-control=sitemap-item-editor]').data('fieldName')
```

**Review by bennothommo — APPROVED** [review]
Nice one, @mjauvin!

**Comment by mjauvin** [comment]
Yes, it has been tested.
